#define SCALE 30

#define VELOCITYITERATIONS 10
#define POSITIONITERATIONS 10

#define CONST_GRAVITATION 10
# define ZOOM 10

#define TEXTUREMUR "Image/cb.bmp"

#define SUN_RADIUS 1500
#define SUN_SCALE 4
#define SUN_TEXTURE "sun"
#define SUN_GRAVIVITYFAC 64

#define MOON_RADIUS 600
#define MOON_SCALE 0.2
#define MOON_TEXTURE "moon"
#define MOON_GRAVIVITYFAC 4


#define MERCURE_RADIUS 600
#define MERCURE_SCALE 1
#define MERCURE_TEXTURE "mercure"
#define MERCURE_GRAVIVITYFAC 0
#define MERCURE_STARTPOS 30000
#define MERCURE_STARTSPEED 44350


#define VENUS_RADIUS 700   
#define VENUS_SCALE 1
#define VENUS_TEXTURE "venus" 
#define VENUS_GRAVIVITYFAC 0
#define VENUS_STARTPOS 50000
#define VENUS_STARTSPEED 47000


#define EARTH_RADIUS 750
#define EARTH_SCALE 1
#define EARTH_TEXTURE "earth"
#define EARTH_GRAVIVITYFAC 0
#define EARTH_STARTPOS 70000
#define EARTH_STARTSPEED 51700


#define WEAPONS01_RADIUS 25
#define WEAPONS01_SCALE 5
#define WEAPONS01_TEXTURE "weapons01"
#define WEAPONS01_GRAVIVITYFAC 0

